Document: org.sea-group.raa-1.0.25
Title: Debian org.sea-group.raa-1.0.25 Manual
Author: <insert document author here>
Abstract: This manual describes what org.sea-group.raa-1.0.25 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/org.sea-group.raa-1.0.25/org.sea-group.raa-1.0.25.sgml.gz

Format: postscript
Files: /usr/share/doc/org.sea-group.raa-1.0.25/org.sea-group.raa-1.0.25.ps.gz

Format: text
Files: /usr/share/doc/org.sea-group.raa-1.0.25/org.sea-group.raa-1.0.25.text.gz

Format: HTML
Index: /usr/share/doc/org.sea-group.raa-1.0.25/html/index.html
Files: /usr/share/doc/org.sea-group.raa-1.0.25/html/*.html
